### ISSUE TITLE
Client user agent/version is reported incorrectly as "c/1.1.0-beta.1(FreeRTOS)"

### ISSUE THREAD

**Issue by wickste** [Azure/azure-iot-middleware-freertos#223]
When using the latest samples I noticed that my device reports "c/1.1.0-beta.1(FreeRTOS)". This is unexpected since this is no longer in pre-release state.

**Comment by danewalton** [comment]
This is expected behavior. We use the same release procedure as the Azure SDK for C which is roughly the following:

1) Cut off check ins for the repo and have it in a verified working state.
2) Change the user agent to the desired label (if it's an official release, it won't have a beta tag). Let's take 1.0.0 for example. So the user agent becomes "c/1.0.0(FreeRTOS)"
3) [Release the repo with that tag](https://github.com/Azure/azure-iot-middleware-freertos/blob/1.0.0/source/include/azure_iot_version.h).
4) Immediately bump the version to a beta for the next release we believe we will have (in this case, next release will likely be `1.1.0` so it will be in beta until the release).

Essentially, the main branch will always be in a "beta" state as it is a WIP for all features in an official release. Once it's an official release, we quickly mark it as official, release, then move on to the beta for the next release.

Let me know if that wasn't explained as well as it could have.
