### ISSUE TITLE
Issue with Group enrollment for X.509 certificate

### ISSUE THREAD

**Issue by ramanijaldeep** [Azure/azure-iot-middleware-freertos#254]
Device provisioning services (DPS) are not able to provision the device with enrollment group service for X.509 certificate attestation.

Reference
https://github.com/Azure-Samples/iot-middleware-freertos-samples/issues/225
https://learn.microsoft.com/en-us/answers/questions/998659/device-provisioning-via-enrollment-group.html

**Comment by KZeronimo** [comment]
Any updates on this item - we have a project where the azure-iot-middleware-freertos is being used, and the end goal is to have the device authenticate utilizing enrollment group service for X.509 certificate attestation.

**Comment by KZeronimo** [comment]
Hi @hauserkristof - thank you for the offer I would be interested in taking you up on that!

**Comment by hauserkristof** [comment]
Okay @KZeronimo you can reach me on [kristof.hauser@imm-data.com](mailto:kristof.hauser@imm-data.com).

Next monday or tuesday (31, 01) seems quite open for me :)

**Comment by ramanijaldeep** [comment]
Hi @hauserkristof 
Thank you for your reply and offer. Also, I am interested in that. Good to hear that you are happy to help. 🙂

**Comment by danewalton** [comment]
Sorry for the late response. I was just able to do a group enrollment using X509 certificates using our middleware:

![image](https://user-images.githubusercontent.com/36710865/221977939-6dffe5e8-f10e-47aa-9784-fbc260f69735.png)

Are there any further details that can be provided here or further questions? Otherwise I'll go ahead and close it since this was just verified.
