### ISSUE TITLE
Remove DPS payload creation once embedded SDK has it

### ISSUE THREAD

**Issue by hihigupt** [Azure/azure-iot-middleware-freertos#63]
Move following implementation to Embedded sdk:
https://github.com/Azure/azure-iot-middleware-freertos/blob/4c2ca23ad09e399788ff7630a7470dad6f60b69b/source/azure_iot_provisioning_client.c#L260

**Comment by jspaith** [comment]
I've completed work, its available [here](https://github.com/jspaith/azure-sdk-for-c/tree/proviosining_payload/) on embedded branch.

It's not ready for PR yet since I need to test E2E against IoT Central on the feature/iot_pnp_stage branch in embedded side.  

You guys should probably try out too before it gets burned into embedded SDK.  It's probably ready for you to do e2e now if you just can't wait on this one (would couldn't?:)) but otherwise I can go 1st on my side for e2e test.
