### ISSUE TITLE
Add QOS option for telemetry

### ISSUE THREAD

**Issue by danewalton** [Azure/azure-iot-middleware-freertos#80]
https://github.com/Azure/azure-iot-middleware-freertos/pull/60#discussion_r609132198

**Comment by hihigupt** [comment]
Options:
1.  Macro to support QoS level of telemetry.
2. Client Init of IoTHub deciding the support of telemetry.
3. Send telemetry api of IoTHub client taking QoS param and letting each caller decide QoS of telemetry.

**Comment by tawalke** [comment]
I want to ensure we all are on the same page of workflow for this so adding these QoS workflows here: 
QoS0
![Screenshot_20210415-164702_Chrome](https://user-images.githubusercontent.com/2299606/114959608-5a462800-9e33-11eb-9a56-9485b924bcaa.jpg)

QoS 1
![Screenshot_20210415-164320_Chrome](https://user-images.githubusercontent.com/2299606/114959657-7053e880-9e33-11eb-9fa9-10fbb73a0ad6.jpg)


QoS 2
![Screenshot_20210415-164617_Chrome](https://user-images.githubusercontent.com/2299606/114959682-7ea20480-9e33-11eb-9a0d-e79e248a1bd6.jpg)

**Comment by jspaith** [comment]
My 2 cents:
* I think the application should be able to decide QoS level per send, not set either at compile or "global-per handle."  The scenarios is around composition because there could be legit different needs.  E.G. the thermostat is fine sending "Current Temp" with QoS0 to simplify things because if it's dropped another one is coming 5 minutes from now anyway.  But "thermostatVoltageShortedOut" event the application would add explicit retry logic at their layer if the message isn't ACK'd in a timely matter.

* Happy QoS2 is being brought up.  To my knowledge we've never been asked (I looked at classic C and C# repos).  Do we need here?  Would it be OK if we could "see an architectural path to add QoS2 without implementing for GA?"

**Comment by wduraes** [comment]
QoS 2: Currently IoT Hub does not support QoS2 [link to article](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support#sending-device-to-cloud-messages) and if a device tries to publish a telemetry message with QoS 2 the network connection is closed. This is one of the reasons why we never hear about that. This should be a non-goal for the middleware: no support from platform = no support from SDK. If this change in the future we can revisit.
